services:

  # Person service

  person-postgres:
    image: postgres:17
    container_name: person-postgres
    environment:
      POSTGRES_USER: person_postgres
      POSTGRES_PASSWORD: person_postgres
      POSTGRES_DB: person
    volumes:
      - person_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U person_postgres" ]
      interval: 10s
      timeout: 5s
      retries: 20

  person-postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: person-postgres-exporter
    depends_on:
      person-postgres:
        condition: service_healthy
    environment:
      DATA_SOURCE_NAME: postgresql://person_postgres:person_postgres@person-postgres:5432/person?sslmode=disable
    ports:
      - "9188:9187"

  # Transaction Service

  transaction-postgres:
    image: postgres:17
    container_name: transaction-postgres
    environment:
      POSTGRES_USER: transaction_postgres
      POSTGRES_PASSWORD: transaction_postgres
      POSTGRES_DB: transaction
    volumes:
      - transaction_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U transaction_postgres" ]
      interval: 10s
      timeout: 5s
      retries: 20

  transaction-postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: transaction-postgres-exporter
    depends_on:
      transaction-postgres:
        condition: service_healthy
    environment:
      DATA_SOURCE_NAME: postgresql://transaction_postgres:transaction_postgres@transaction-postgres:5432/transaction?sslmode=disable
    ports:
      - "9189:9187"

  # Account service

  account-postgres:
    image: postgres:17
    container_name: account-postgres
    environment:
      POSTGRES_USER: account_postgres
      POSTGRES_PASSWORD: account_postgres
      POSTGRES_DB: account
    volumes:
      - account_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U account_postgres" ]
      interval: 10s
      timeout: 5s
      retries: 20

  account-postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: account-postgres-exporter
    depends_on:
      account-postgres:
        condition: service_healthy
    environment:
      DATA_SOURCE_NAME: postgresql://account_postgres:account_postgres@account-postgres:5432/account?sslmode=disable
    ports:
      - "9190:9187"

  # API Gateway

  redis-gateway:
    image: redis:7-alpine
    container_name: redis-gateway
    command: "--requirepass redis-gateway"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-gateway-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-gateway-exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis://redis:6379"
      REDIS_PASSWORD: "redis-gateway"
    depends_on:
      redis-gateway:
        condition: service_healthy

  # Keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command: start-dev --import-realm --metrics-enabled=true
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      JAVA_OPTS: -Dkeycloak.migration.usersExportStrategy=REALM_FILE
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak_postgres
      KC_DB_PASSWORD: keycloak_postgres
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
    volumes:
      - ./infrastructure/keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9000/health/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 30

  keycloak-postgres:
    image: postgres:17
    container_name: keycloak-postgres
    environment:
      POSTGRES_USER: keycloak_postgres
      POSTGRES_PASSWORD: keycloak_postgres
      POSTGRES_DB: keycloak
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak_postgres" ]
      interval: 10s
      timeout: 5s
      retries: 20

  keycloak-postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: keycloak-postgres-exporter
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    environment:
      DATA_SOURCE_NAME: postgresql://keycloak_postgres:keycloak_postgres@keycloak-postgres:5432/keycloak?sslmode=disable
    ports:
      - "9191:9187"

  # Kafka

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    ports:
      - "8082:8081"
    volumes:
      - schema_registry_data:/etc/schema-registry
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/subjects" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    ports:
      - "9308:9308"
    restart: unless-stopped
    command:
      - "--kafka.server=kafka:9092"
    depends_on:
      kafka:
        condition: service_healthy

  # Nexus

  nexus:
    image: sonatype/nexus3:3.76.0
    container_name: nexus
    ports:
      - "8083:8081"
    environment:
      NEXUS_SECURITY_INITIAL_PASSWORD: admin
      NEXUS_SECURITY_RANDOMPASSWORD: false
    volumes:
      - nexus-data:/nexus-data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status" ]
      interval: 5s
      timeout: 10s
      retries: 30

  # Observability

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:9090/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 5

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./infrastructure/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_data:/loki
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3100/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    user: root
    ports:
      - "9080:9080" # HTTP interface
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP http
    volumes:
      - ./infrastructure/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log:ro
    environment:
      GRAFANA_LOKI_URL: http://loki:3100/loki/api/v1/push
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:9080
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]
    volumes:
      - ./infrastructure/tempo/tempo.yaml:/etc/tempo/tempo.yaml
      - tempo_data:/var/tempo
    ports:
      - "3200:3200"

  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_healthy
      loki:
        condition: service_healthy
      tempo:
        condition: service_started
      alloy:
        condition: service_started
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_METRICS_ENABLED: "true"
    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 10


volumes:
  person_data:
  transaction_data:
  account_data:
  keycloak_data:
  loki_data:
  tempo_data:
  schema_registry_data:
  nexus-data: