global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: keycloak
    metrics_path: /metrics
    static_configs:
      - targets: [ 'keycloak:9000' ]

  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: [ 'grafana:3000' ]

  - job_name: alloy
    metrics_path: /metrics
    static_configs:
      - targets: [ 'alloy:9080' ]

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: tempo
    metrics_path: /metrics
    static_configs:
      - targets: [ 'tempo:3200']

  - job_name: kafka
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: redis-gateway
    static_configs:
      - targets: ['redis-gateway-exporter:9121']

  - job_name: person-postgres
    static_configs:
      - targets: ["person-postgres-exporter:9187"]

  - job_name: transaction-postgres
    static_configs:
      - targets: ["transaction-postgres-exporter:9187"]

  - job_name: account-postgres
    static_configs:
      - targets: ["account-postgres-exporter:9187"]

  - job_name: keycloak-postgres
    static_configs:
      - targets: ["keycloak-postgres-exporter:9187"]